#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=app_password="$APP_DB_PASSWORD" <<'SQL'
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE ROLE kirh_app LOGIN PASSWORD :'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
GRANT CONNECT ON DATABASE :DBNAME TO kirh_app;
GRANT USAGE ON SCHEMA public TO kirh_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kirh_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO kirh_app;
ALTER DEFAULT PRIVILEGES FOR ROLE kirh_migrator IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kirh_app;
ALTER DEFAULT PRIVILEGES FOR ROLE kirh_migrator IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO kirh_app;
SQL
